### ISSUE TITLE
Если Вы готовы сдавать задание проверьте, все ли пункты Вы сделали

### ISSUE THREAD

**Issue by JSMonk** [boldevelop/wysiwig-task#2]
```
1. Размещаете репозиторий на GitHub / GitLab (не делайте форк этого репозитория, если опасаетесь, что конкуренты "подсмотрят")
2. Добавляете в коллабораторы репозитория @xanf и @jsmonk
3. Создаете issue в своем репозитории "просьба проверить тестовое задание" и назначаете его @xanf
4. Все ревью будет выполнено в issue
```

**Comment by boldevelop** [comment]
> ```
> 1. Размещаете репозиторий на GitHub / GitLab (не делайте форк этого репозитория, если опасаетесь, что конкуренты "подсмотрят")
> 2. Добавляете в коллабораторы репозитория @xanf и @jsmonk
> 3. Создаете issue в своем репозитории "просьба проверить тестовое задание" и назначаете его @xanf
> 4. Все ревью будет выполнено в issue
> ```

Готов сдавать, но чтоб выполнить 3 пункт необходимо назначить issue на @xanf, поэтому ждал принятия приглашения в коллабораторы.
Создал issue "просьба проверить тестовое задание" и назначил на Вас @JSMonk .
