### ISSUE TITLE
просьба проверить тестовое задание

### ISSUE THREAD

**Issue by boldevelop** [boldevelop/wysiwig-task#3]

**Comment by JSMonk** [comment]
1. При вставке содержимого в Microsoft Office Online стили не сохраняются:
<img width="193" alt="Screen Shot 2021-01-13 at 3 49 22 PM" src="https://user-images.githubusercontent.com/10776615/104460781-3286c000-55b7-11eb-9d7f-9cc59da3b288.png">
<img width="597" alt="Screen Shot 2021-01-13 at 3 49 29 PM" src="https://user-images.githubusercontent.com/10776615/104460785-331f5680-55b7-11eb-9f02-5cda973d791d.png">

2. Комбинация декораций не работает:

https://user-images.githubusercontent.com/10776615/104460957-5cd87d80-55b7-11eb-84d4-2a2b0defa842.mov

**Comment by boldevelop** [comment]
Прошу проверить еще раз @JSMonk 
Исправил.

Еще добавил отмену стилизации, но оно не идеально работает только в определенном случае, выделил-применил-отменил.
Так же есть проблема с созданием дом елементов, если поочередно нажимать bold и italic.
Не знаю насколько должно быть готово тестовое, чтоб считалось завершенным, поэтому вынес это сюда.

**Comment by JSMonk** [comment]
Здравствуйте, Владислав.
Стилизация все еще не сохраняется при копировании в Microsoft Office Online:
<img width="181" alt="Screen Shot 2021-01-16 at 1 07 18 AM" src="https://user-images.githubusercontent.com/10776615/104787096-5e609c00-5797-11eb-818a-0c0c61a13c87.png">
<img width="602" alt="Screen Shot 2021-01-16 at 1 07 15 AM" src="https://user-images.githubusercontent.com/10776615/104787097-5f91c900-5797-11eb-9cdc-c2b0e0a3b007.png">

**Comment by boldevelop** [comment]
Доброго времени суток, Артем @JSMonk .
Проше проверить задание.

Из исправлений:
* Улучшил генерируемую разметку html при применении стилей.
* Проблему с MS word решил топорно, для заголовков добавил инлайновый `font-size`

**Comment by JSMonk** [comment]
Здравствуйте, Владислав.
1. У Вас присутствует возможность редактировать элементы вне contenteditable:

https://user-images.githubusercontent.com/10776615/104847152-16508f00-58e7-11eb-87e1-08831ed9940d.mov

2. Также, прошу попробовать использовать уже заданные в `styles/editor.css` стили для заголовков, italic и bold (относительные единицы нельзя менять на абсолютные!!!)

Если поправите это, задание будет зачтено.
Хорошая работа 👍

**Comment by boldevelop** [comment]
Доброго времени суток, Артем @JSMonk.

1. Исправил редактирование контента вне редактора.
2. Убрал инлайновые стили из редактора. Реализовал на событиях copy, cut, paste (при вставке сохранил валидацию браузера).
При копировании/вырезании все еще инланю стили, но при вставке обратно их в редактор вырезаю.
Прописываю в `style `размер, стиль шрифта, и italic и bold, так как эмпирическим путем определил на, что реагирует MS Word при такой реализации. `'font-family: Helvetica, Arial, sans-serif;'` Инлайнится из этих же соображений, если указывать `"Haas Grot Text R Web", "Helvetica Neue", Helvetica, Arial, sans-serif;` то MS Word оставляет Arial (не реагирует).

Остальное: добавил jsDoc

**Comment by JSMonk** [comment]
Здравствуйте, Владислав.
1. При копировании стилей меняется цвет заголовков:
<img width="457" alt="Screen Shot 2021-01-19 at 10 03 26 PM" src="https://user-images.githubusercontent.com/10776615/105086997-7dff0980-5aa2-11eb-9d33-a3422f495e43.png">
<img width="225" alt="Screen Shot 2021-01-19 at 10 02 30 PM" src="https://user-images.githubusercontent.com/10776615/105087003-7f303680-5aa2-11eb-9be5-c43e96248da7.png">

2. Стили все еще заинлайнены:
```typescript
const fontFamily = 'font-family: Helvetica, Arial, sans-serif;'
const header1Style = `font-size: 24px; ${fontFamily}`;
const header2Style = `font-size: 19px; ${fontFamily}`;
const boldStyle = `font-weight: 900; ${fontFamily}`;
const italicStyle = `font-style: italic; ${fontFamily}`;
```

**Comment by boldevelop** [comment]
Доброго времени суток, Артем @JSMonk.
Проше проверить задание.

Из исправлений: переделал на `getComputedStyle`

**Comment by JSMonk** [comment]
Здравствуйте, Владислав.
1. Пропал placeholder:
<img width="659" alt="Screen Shot 2021-01-20 at 3 17 28 PM" src="https://user-images.githubusercontent.com/10776615/105180026-b77f5580-5b32-11eb-8c9f-75f91f147058.png">

2. При вырезании содержимого и вставке в Microsoft Office Online меняется цвет заголовков:
<img width="270" alt="Screen Shot 2021-01-20 at 3 18 47 PM" src="https://user-images.githubusercontent.com/10776615/105180250-fad9c400-5b32-11eb-80f3-cdacf5b716a3.png">
<img width="666" alt="Screen Shot 2021-01-20 at 3 19 33 PM" src="https://user-images.githubusercontent.com/10776615/105180252-fb725a80-5b32-11eb-8bac-c78ebbc6cb71.png">

3. Кобминация стилей не работает (сначала сделал italic, а потом все заголовком):
<img width="599" alt="Screen Shot 2021-01-20 at 3 20 59 PM" src="https://user-images.githubusercontent.com/10776615/105180380-2ceb2600-5b33-11eb-9f09-93d3627e976b.png">

**Comment by boldevelop** [comment]
@JSMonk.
1. Поправил
По остальным можете подробней написать, не могу воспроизвести 2 (копируются, вырезается / вставляется без смены цвета)
По 3 не совсем понимаю, какой алгоритм чтоб воспроизвести

**Comment by JSMonk** [comment]
Сначала я выделил `italic header` и применил кнопку italic, а потом весь текст и применил h1.

**Comment by boldevelop** [comment]
Доброго времени суток, Артем @JSMonk.
Исправил замечания. Прошу проверить задание.

**Comment by JSMonk** [comment]
Здравствуйте, Владислав.
Все хорошо, задание принято.
Вы славно потрудились 👍

Можно Вашу почту (если подписаны были на Patreon - то ту же что и на патреоне) и telegram-контакт (номер или ник, все-равно) для дублирования сообщений.

Пройдет некоторое количество времени (мы сдвинем старт на неделю вперед) и Вы получите ссылку на оплату и мы сообщим Вам дальнейшие шаги.

**Comment by boldevelop** [comment]
@JSMonk Спасибо!
Почта: boldakov.vladislav@gmail.com
Телеграм: `@boldakov_v`

**Comment by xanf** [comment]
Обработано, сегодня получите письмо
